#ifndef BSF_ARDUINO_WEIGHTSTATION_DISPLAY_H
#define BSF_ARDUINO_WEIGHTSTATION_DISPLAY_H

enum displayRecipeStates { START = 0, START_WITH_RECIPE, SELECT_COMP, UPDATE };

#endif //BSF_ARDUINO_WEIGHTSTATION_DISPLAY_H
